global.pets = 
[
	obj_pet_flicky,
	obj_pet_chao,
	obj_pet_metal,
	obj_pet_dadol,
	obj_pet_majin,
	obj_pet_mknux,
	obj_pet_egg,
	obj_pet_secret
];

global.petPallettes = 
[
	scr_palette([ #8484e7, #4242a5, #212184 ]),
	scr_palette([ #addef8, #2ebee9, #0e6d89, #ecde2f, #dcb936, #985000 ]),
	scr_palette([ #e00000, #800000 ]),
	scr_palette([ #e00000, #800000 ]),
	scr_palette([ #000022, #000090, #482490, #6c48b4 ]),
	scr_palette([ #ff0000, #700000, #ba0000 ]),
	scr_palette([ #fc0000, #900000 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
	scr_palette([ 0 ]),
];